/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ufp.inf.sd.rmi.dropbox.client;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author antonioferreira
 */
public class DropboxClientFolderGUI extends javax.swing.JFrame implements WindowListener {

    private final DropboxClientImpl dbclientImpl;
    private final DropboxClientGroupGUI dbgui;
    String groupName;

    /**
     * Creates new form DropboxClientFolderGUI
     */
    /**
     * Creates new form DropboxClientFolderGUI
     *
     * @param dbclientImpl
     */
    public DropboxClientFolderGUI(DropboxClientImpl dbclientImpl, String groupName, DropboxClientGroupGUI dbgui) throws RemoteException {
        this.dbclientImpl = dbclientImpl;
        this.groupName = groupName;
        this.dbgui = dbgui;
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.addWindowListener(this);
        System.out.println("---- group name -----" + groupName);
        File[] afile = dbclientImpl.getDbserverRI().listDir(groupName, "");
        DefaultListModel listModel = new DefaultListModel();
        int i = 0;
        for (int j = afile.length; i < j; i++) {
            listModel.addElement(afile[i].getName());
        }
        jListGroupFolders.setModel(listModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextNewFolder = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonCreateFolder = new javax.swing.JButton();
        jButtonMoveFolder = new javax.swing.JButton();
        jButtonRenameFolder = new javax.swing.JButton();
        jButtonDeleteFolder = new javax.swing.JButton();
        jButtonExitFolder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGroupFolders = new javax.swing.JList<>();
        jButtonExitGroup = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextNewFolder.setText("New Folder");
        jTextNewFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNewFolderActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCreateFolder.setText("Create");
        jButtonCreateFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFolderActionPerformed(evt);
            }
        });

        jButtonMoveFolder.setText("Move");
        jButtonMoveFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveFolderActionPerformed(evt);
            }
        });

        jButtonRenameFolder.setText("Rename");
        jButtonRenameFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRenameFolderActionPerformed(evt);
            }
        });

        jButtonDeleteFolder.setText("Delete");
        jButtonDeleteFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteFolderActionPerformed(evt);
            }
        });

        jButtonExitFolder.setText("Back");
        jButtonExitFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitFolderActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListGroupFolders);

        jButtonExitGroup.setText("Exit Group");
        jButtonExitGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitGroupActionPerformed(evt);
            }
        });

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 106, Short.MAX_VALUE)
                                        .addComponent(jButtonDeleteFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextNewFolder))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jButtonExitFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonCreateFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonExitGroup)
                                    .addComponent(jButtonOpen))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonMoveFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRenameFolder)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonOpen)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCreateFolder)
                            .addComponent(jTextNewFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRenameFolder)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMoveFolder))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExitFolder)
                            .addComponent(jButtonDeleteFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExitGroup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNewFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNewFolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewFolderActionPerformed

    private void jButtonCreateFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFolderActionPerformed
        try {

            File[] afile;

            dbclientImpl.getDbserverRI().makeDir(groupName, jTextNewFolder.getText());

            DefaultListModel listModel = new DefaultListModel();
            int i = 0;
            afile = dbclientImpl.getDbserverRI().listDir(groupName, "");
            for (int j = afile.length; i < j; i++) {
                listModel.addElement(afile[i].getName());
            }
            jListGroupFolders.setModel(listModel);
        } catch (RemoteException ex) {
            Logger.getLogger(DropboxClientFolderGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCreateFolderActionPerformed

    private void jButtonExitGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitGroupActionPerformed
        setVisible(false);
        dbgui.setVisible(true);


    }//GEN-LAST:event_jButtonExitGroupActionPerformed

    private void jButtonRenameFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRenameFolderActionPerformed
        try {
            dbclientImpl.getDbserverRI().renameDir(groupName, jListGroupFolders.getSelectedValue(), jTextNewFolder.getText());
            
            File[] afile;
            DefaultListModel listModel = new DefaultListModel();
            int i = 0;
            afile = dbclientImpl.getDbserverRI().listDir(groupName, "");
            for (int j = afile.length; i < j; i++) {
                listModel.addElement(afile[i].getName());
            }
            jListGroupFolders.setModel(listModel);
        } catch (RemoteException ex) {
            Logger.getLogger(DropboxClientFolderGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonRenameFolderActionPerformed

    private void jButtonMoveFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveFolderActionPerformed
        
    }//GEN-LAST:event_jButtonMoveFolderActionPerformed

    private void jButtonDeleteFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteFolderActionPerformed
        try {
            dbclientImpl.getDbserverRI().removeDir(groupName, jListGroupFolders.getSelectedValue());
            File[] afile;
            DefaultListModel listModel = new DefaultListModel();
            int i = 0;
            afile = dbclientImpl.getDbserverRI().listDir(groupName, "");
            for (int j = afile.length; i < j; i++) {
                listModel.addElement(afile[i].getName());
            }
            jListGroupFolders.setModel(listModel);
        } catch (RemoteException ex) {
            Logger.getLogger(DropboxClientFolderGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jButtonDeleteFolderActionPerformed

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
         try {
        File[] afile;
            DefaultListModel listModel = new DefaultListModel();
            int i = 0;
       
            afile = dbclientImpl.getDbserverRI().listDir(groupName, jListGroupFolders.getSelectedValue());
            for (int j = afile.length; i < j; i++) {
                listModel.addElement(afile[i].getName());
            }
            jListGroupFolders.setModel(listModel);
        } catch (RemoteException ex) {
            Logger.getLogger(DropboxClientFolderGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonExitFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitFolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitFolderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateFolder;
    private javax.swing.JButton jButtonDeleteFolder;
    private javax.swing.JButton jButtonExitFolder;
    private javax.swing.JButton jButtonExitGroup;
    private javax.swing.JButton jButtonMoveFolder;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonRenameFolder;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jListGroupFolders;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextNewFolder;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
